export { default as HomePage } from "./Home";
export { default as SignupPage } from "./Signup";
export { default as SigninPage } from "./Signin";
export { default as CreateLessonPage } from "./CreateLesson";
export { default as UpdateLessonPage } from "./UpdateLesson";
export { default as CourseDetailPage } from "./CourseDetail";
export { default as LessonDetailPage } from "./LessonDetail";
export { default as TestTeacherPage } from "./TestTeacher";
export { default as NotFoundPage } from "./NotFound";
